### ISSUE TITLE
Please don't direct people to a donate page when they try to view the survey results

### ISSUE THREAD

**Issue by LoganDark** [StateOfJS/Monorepo#50]
This isn't a good practice. It annoys potential buyers into avoiding donation altogether, because they didn't even get what they came for before you started begging. Putting a donate link in the sidebar/footer is a much better, more generally accepted way of providing people who want to donate with the means of doing so.

**Comment by SachaG** [comment]
Sorry, but what are you talking about?

**Comment by LoganDark** [comment]
When you visit the State of CSS website (for example, through the email newsletter), you land on [this page](https://2021.stateofcss.com/en-US/), which is the home page of the site. When you click the Start button to view the results, [you are instead directed to a donate page](https://2021.stateofcss.com/en-US/tshirt/) before being allowed to continue to the actual results.

The sidebar allows skipping this page but it's not very obvious that it exists in the first place.

**Comment by SachaG** [comment]
First of all that is not what the word "donation" means. Unless you think you "donate" to your supermarket every time you go grocery shopping? In which case the IRS would like a word with you.

That being said I'm deeply sorry that my "begging" has annoyed you. Here I was, so focused on base materialistic needs like "earning money" and "paying rent" that I completely forgot to even consider that I might thus be tainting pure souls like yours. Because of my carelessness, your illusion that the entire world exists for the sole purpose of showering you with free entertainment was shattered, and that is unacceptable. 

Obviously this won't do. Please accept my letter of resignation.

**Comment by LoganDark** [comment]
The fact that you are accepting donations (or, sorry, accepting _support_ in the form of money leaving my bank account and a cut entering yours) I have no problem with. The reason I raised this issue is because the _method_ you are using to ask for said support is quite intrusive and might scare off potential donors who haven't yet made up their mind.
